# Generated by Django 3.1.4 on 2023-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('3', '교역자'), ('2', '임원'), ('1', '정회원'), ('0', '준회원')], max_length=20, null=True, verbose_name='등급'),
        ),
    ]
