# Generated by Django 3.1.14 on 2022-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice_feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=5000)),
                ('writer', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('view', models.IntegerField(default=0)),
                ('like_view', models.IntegerField(default=0)),
            ],
        ),
    ]
