# Generated by Django 3.1.4 on 2023-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0002_alter_share_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_feed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
